### 












Business Problem Statement
A leading retail company wants to better understand its customers’ shopping behavior in order
to improve sales, customer satisfaction, and long-term loyalty. The management team has
noticed changes in purchasing patterns across demographics, product categories, and sales
channels (online vs. offline). They are particularly interested in uncovering which factors, such
as discounts, reviews, seasons, or payment preferences, drive consumer decisions and repeat
purchases.
You are tasked with analyzing the company’s consumer behavior dataset to answer the
following overarching business question:
“How can the company leverage consumer shopping data to identify trends, improve
customer engagement, and optimize marketing and product strategies?”

## Deliverables
1. Data Preparation & Modeling (Python): Clean and transform the raw dataset for
analysis.
2. Data Analysis (SQL): Organize the data into a structured format, simulate business
transactions, and run queries to extract insights on customer segments, loyalty, and
purchase drivers.
3. Visualization & Insights (Power BI): Build an interactive dashboard that highlights key
patterns and trends, enabling stakeholders to make data-driven decisions.
4. Report and Presentation: Write a clear project report summarizing your key findings
and business recommendations. Prepare a presentation that visually communicates
insights and actionable recommendations to stakeholders.
5. GitHub Repository: Include all Python scripts, SQL queries, and dashboard files in a
well-structured repository.

In [155]:
import pandas as pd

df= pd.read_csv("customer_shopping_behavior.csv")

In [157]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [158]:
df.isnull()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [160]:
df.shape

(3900, 18)

In [161]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [162]:
# missing values

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [163]:
# Since review rating is numerical

# handling missing values

df['Review Rating']= df['Review Rating'].fillna(df['Review Rating'].median())

In [164]:
df['Review Rating'].isnull().sum()

0

In [166]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [167]:
# we can see in the data--- the snakecases
# so all should be lowercase
## why to change? --- it make code easier tp read & consistence 

df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [170]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [172]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [175]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [177]:
# we need to know the age group for classification of shopping category
# we create age_group

# Why pd.cut()?? --- to create meaningful age segments aligned with business understanding instead of purely disturbution based binning

df['age_group']=pd.qcut(df['age'], q=4, labels=['Adult','Young Adult','Middle-aged','Senior'])

In [179]:
df[['age','age_group']].head(-1)

      age    age_group
0      55  Middle-aged
1      19        Adult
2      50  Middle-aged
3      21        Adult
4      45  Middle-aged
...   ...          ...
3894   66       Senior
3895   40  Young Adult
3896   52  Middle-aged
3897   46  Middle-aged
3898   44  Young Adult

[3899 rows x 2 columns]

In [182]:
# creating purchase_frequency_days
freq_mapping={
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}
df['purchase_frequency_days']= df['frequency_of_purchases'].map(freq_mapping)

In [184]:
df[['purchase_frequency_days','frequency_of_purchases']].head(40)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly
15                       30                Monthly
16                       14              Bi-Weekly
17                       90              Quarterly
18                        7                 Weekly
19                       14              Bi-Weekly
20                       90         Every 3 Months
21                       90              Quarterly
22                      365               Annually
23                        7                 Weekly
24                        7                 Weekly
25                      365               Annually
26                      365               Annually
27                       90         Every 3 Months
28                       90         Every 3 Months
29                        7                 Weekly
30                       30                Monthly
31                       30                Monthly
32                      365               Annually
33                       90              Quarterly
34                       90              Quarterly
35                       14              Bi-Weekly
36                       14            Fortnightly
37                        7                 Weekly
38                       90         Every 3 Months
39                       30                Monthly

In [186]:
df[['promo_code_used','discount_applied']].head(5)

  promo_code_used discount_applied
0             Yes              Yes
1             Yes              Yes
2             Yes              Yes
3             Yes              Yes
4             Yes              Yes

In [188]:
### discount_apply and promocode_used is commonly same...
## as if you use discount_apply obviously promocode is used 
##but sometimes companies might be use discounts without promocode like seasonal changes,exclusive discounts for subscribed ones!!

In [190]:
(df['promo_code_used']==df['discount_applied']).all()

True

In [191]:
## that means it remains of same information in both columns so we delete / drop promocode_used
df=df.drop('promo_code_used',axis=1)

# df.columns

In [195]:
!pip install pymysql

Requirement already satisfied: pymysql in d:\anaconda\lib\site-packages (1.1.2)

In [196]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Srivarsha%401234@localhost:3306/customer_behaviour_analysis"
)
print("Connection ready!")

Connection ready!

In [198]:
df.to_sql(
    name="customer_shopping",
    con=engine,
    if_exists="replace",
    index=False,
    chunksize=100   # smaller = safer
)

print("Done!")

Done!